### ISSUE TITLE
Assets losing "metadata" property

### ISSUE THREAD

**Issue by kennedyrose** [stackbithq/sourcebit-source-sanity#5]
Not sure if it could be a problem form anyone else, but we use `asset.metadata.dimensions` to maintain the aspect ratio of the element while the image lazy loads in. But it seems that this plugin removes the metadata property from the asset object at some point.

**Comment by eduardoboucas** [comment]
Hi @kennedyrose.

I'm really sorry for the really delayed response. Somehow I didn't get a notification for this issue. 😞 

I have created #11, which stops the plugin from removing the `metadata` block. We should be able to get it merged and released in the coming days. I'll keep this issue updated.

Thanks!
